version: '2'
services:
    web:
        build: 
          context: .
          dockerfile: ./Dockerfile
        image: 301180448685.dkr.ecr.us-east-1.amazonaws.com/art-store-project:art_shop
        command: gunicorn app:app --bind 0.0.0.0:5002
        ports:
          - "5002:5002"
        volumes:
          - ./art_shop/:/usr/src/app/
        expose: 
          - 5002
        environment:
          DB_NAME: '${DB_NAME}'
          DB_PASSWORD: "${DB_PASS}"
          DB_HOST: "${DB_HOST}"
          DB_PORT: 5432
          DB_DATABASE: postgres
          VIRTUAL_HOST: "${ec2}"
          VIRTUAL_PORT: 5002





       
      


# version: '3.4'

# services:
#   artshop:
#     image: artshop
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     ports:
#       - 5002:5002


