version: '2'
services:
    web:
        build: 
          context: .
          dockerfile: ./Dockerfile
        image: 301180448685.dkr.ecr.us-east-1.amazonaws.com/art-store-project:art_shop
        command: gunicorn app:app --bind 0.0.0.0:5002
        expose: 
          - 5002
        environment:
          DB_NAME: '${DB_NAME}'
          DB_PASSWORD: "${DB_PASS}"
          DB_HOST: "${DB_HOST}"
          DB_PORT: 5432
          DB_DATABASE: postgres
          VIRTUAL_HOST: "${ec2}"
          VIRTUAL_PORT: 5002
    nginx:
      build: ./nginx
      image: art_shop_nginx
      ports:
        - 5002:80
      depends_on:
        - web





       
      


# version: '3.4'

# services:
#   artshop:
#     image: artshop
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     ports:
#       - 5002:5002


